output:
  sort-results: true

run:
  modules-download-mode: vendor
  timeout: 5m

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
    # Ignore magic numbers in klog.V() calls until we clean them up.
    - linters:
        - gomnd
      source: "klog.V\\("
    # Ignore long generate commands.
    - linters:
        - lll
      source: "^\\/\\/go:generate"
    # Ignore URLs in comments.
    - linters:
        - lll
      source: "http(s)://"
    # Allow use of fmt.Print* functions.
    - linters:
      - forbidigo
      text: "use of `fmt.Printf` forbidden by pattern"
      path: cmd/
    - linters:
      - forbidigo
      text: "use of `fmt.Println` forbidden by pattern"
      path: cmd/

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

# Update list of enabled linters using 'make update-linters'.
linters:
  disable-all: false
  disable:
    # We use different import grouping style than gci forces.
    - gci
    # We still have many globals to get rid of.
    - gochecknoglobals
    # TODOs in the code are OK.
    - godox
    # We do not have clearly defined error types yet.
    - goerr113
    # We do not require all used structs to have all fields initialized.
    - exhaustivestruct
    # We do not care about the memory efficiency really.
    - maligned
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - golint
    - gomnd
    - gomodguard
    - goprintffuncname
    - ineffassign
    - interfacer
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - structcheck
    - stylecheck
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace
    - wrapcheck
    - wsl
